create table if not exists public.parcels (
  id bigint generated by default as identity primary key,
  tracking_number text not null,
  sender_name text not null,
  sender_phone text not null,
  sender_address text not null,
  receiver_name text not null,
  receiver_phone text not null,
  origin text not null,
  destination text not null,
  status text not null default 'Processing',
  received_at timestamp with time zone,
  notes text,
  created_at timestamp with time zone default now()
);

alter table public.parcels enable row level security;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'parcels' and policyname = 'Allow public read access') then
    execute 'create policy "Allow public read access" on public.parcels for select using (true)';
  end if;

  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'parcels' and policyname = 'Allow public insert access') then
    execute 'create policy "Allow public insert access" on public.parcels for insert with check (true)';
  end if;

  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'parcels' and policyname = 'Allow public update access') then
    execute 'create policy "Allow public update access" on public.parcels for update using (true) with check (true)';
  end if;

  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'parcels' and policyname = 'Allow public delete access') then
    execute 'create policy "Allow public delete access" on public.parcels for delete using (true)';
  end if;
end $$;
